"""add reminder_sent to todos

Revision ID: 002
Revises: 29f774bde39a
Create Date: 2026-01-28 02:41:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '002'
down_revision: Union[str, None] = '29f774bde39a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    op.execute("UPDATE todos SET reminder_sent = FALSE")
    op.alter_column('todos', 'reminder_sent', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'reminder_sent')
    # ### end Alembic commands ###
