# Grafana Dashboard - Phase 5
# Production visualization and monitoring

---
# Grafana ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus:9090
        isDefault: true
        editable: true

---
# Grafana Dashboard ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
data:
  # Backend API Dashboard
  backend-dashboard.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Backend API - Phase 5",
        "tags": ["backend", "api", "phase-5"],
        "timezone": "browser",
        "schemaVersion": 16,
        "version": 0,
        "refresh": "10s"
      },
      "overwrite": true,
      "panels": [
        {
          "id": 1,
          "title": "Request Rate",
          "type": "graph",
          "targets": [
            {
              "expr": "rate(http_requests_total[5m])",
              "legendFormat": "{{method}} {{endpoint}}"
            }
          ],
          "gridPos": {"h": 8, "w": 12, "x": 0, "y": 0}
        },
        {
          "id": 2,
          "title": "Request Latency (p95)",
          "type": "graph",
          "targets": [
            {
              "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))",
              "legendFormat": "{{endpoint}}"
            }
          ],
          "gridPos": {"h": 8, "w": 12, "x": 12, "y": 0}
        },
        {
          "id": 3,
          "title": "Tasks Created",
          "type": "stat",
          "targets": [
            {
              "expr": "rate(tasks_created_total[5m])",
              "legendFormat": "Tasks/sec"
            }
          ],
          "gridPos": {"h": 4, "w": 6, "x": 0, "y": 8}
        },
        {
          "id": 4,
          "title": "Tasks Completed",
          "type": "stat",
          "targets": [
            {
              "expr": "rate(tasks_completed_total[5m])",
              "legendFormat": "Tasks/sec"
            }
          ],
          "gridPos": {"h": 4, "w": 6, "x": 6, "y": 8}
        },
        {
          "id": 5,
          "title": "Reminders Sent",
          "type": "stat",
          "targets": [
            {
              "expr": "rate(reminders_sent_total[5m])",
              "legendFormat": "Reminders/sec"
            }
          ],
          "gridPos": {"h": 4, "w": 6, "x": 12, "y": 8}
        },
        {
          "id": 6,
          "title": "Error Rate",
          "type": "graph",
          "targets": [
            {
              "expr": "rate(errors_total[5m])",
              "legendFormat": "{{error_type}} {{endpoint}}"
            }
          ],
          "gridPos": {"h": 8, "w": 12, "x": 0, "y": 12}
        },
        {
          "id": 7,
          "title": "WebSocket Connections",
          "type": "graph",
          "targets": [
            {
              "expr": "sum(websocket_connections_active)",
              "legendFormat": "Active Connections"
            }
          ],
          "gridPos": {"h": 8, "w": 12, "x": 12, "y": 12}
        }
      ]
    }

---
# Grafana Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      serviceAccountName: grafana
      securityContext:
        fsGroup: 472
        runAsGroup: 472
        runAsUser: 472
      containers:
      - name: grafana
        image: grafana/grafana:10.2.2
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: admin-username
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-credentials
              key: admin-password
        - name: GF_SERVER_ROOT_URL
          value: "/grafana"
        - name: GF_INSTALL_PLUGINS
          value: "grafana-piechart-panel"
        volumeMounts:
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: dashboards
          mountPath: /etc/grafana/provisioning/dashboards
        - name: dashboard-data
          mountPath: /var/lib/grafana
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: datasources
        configMap:
          name: grafana-datasources
      - name: dashboards
        configMap:
          name: grafana-dashboards
      - name: dashboard-data
        emptyDir: {}

---
# Grafana Service
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  selector:
    app: grafana

---
# Grafana ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana
  namespace: monitoring

---
# Grafana Secret
apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: monitoring
type: Opaque
stringData:
  admin-username: "admin"
  admin-password: "changeme123"  # Change this in production!

---
# Grafana Ingress (optional - for external access)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - grafana.yourdomain.com
    secretName: grafana-tls
  rules:
  - host: grafana.yourdomain.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana
            port:
              number: 3000
